[Tgbot 290] Create http client user gateway implementation
Tutritp01/TgBot_WebClient pull request #17
Opened 2023-03-02 09:41 UTC by Artem-Metlushko

https://schneidervs.atlassian.net/browse/TGBOT-290

2023-03-04 16:49 UTC, max-java requested changes
ptal with https://github.com/Tutritp01/TgBot_WebClient/pull/21

2023-03-09 11:46 UTC, Sav4ykVladzislau commented on http-client/src/main/resources/application.properties
> +endpoint.web-client=http://localhost:8080
it wasn't supposed to get here.

2023-03-09 12:45 UTC, yurasava approved these changes, later dismissed

2023-03-09 17:47 UTC, yurasava approved these changes, later dismissed

2023-03-10 09:23 UTC, Artem-Metlushko commented on http-client/src/main/resources/application.properties
> +endpoint.web-client=http://localhost:8080
I've deleted

2023-03-10 17:02 UTC, AlexanderYarokhovich approved these changes, later dismissed

2023-03-10 17:10 UTC, schneidervs approved these changes, later dismissed

2023-03-10 18:44 UTC, yurasava approved these changes

2023-03-10 18:45 UTC, schneidervs approved these changes

2023-03-10 18:45 UTC, AlexanderYarokhovich approved these changes

2023-03-10 18:45 UTC, schneidervs approved these changes

2023-03-10 18:52 UTC, Sav4ykVladzislau approved these changes

2023-03-10 18:52 UTC, max-java approved these changes
lgfm

2023-03-10 18:52 UTC, max-java commented on http-client/src/main/java/com/tutrit/httpclient/HttpUserGateway.java
> +            throw new RuntimeException("Can't read getStringHttpResponse", e);// TODO: 07.03.2023
todo what?

2023-03-10 18:56 UTC, merged