[TGBOT-288] Create parent pom and child modules
Tutritp01/TgBot_WebClient pull request #6
Opened 2023-02-05 17:47 UTC by yurasava

https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-288

2023-02-07 06:30 UTC, Sav4ykVladzislau reviewed
lgfm

2023-02-07 09:20 UTC, max-java requested changes
minor comments, otherwise lgfm

2023-02-07 09:20 UTC, max-java commented on .gitignore
> +*.properties
properties files should be in the repository
if you have sensitive data in there - that should be encrypted or replaces with placeholders

2023-02-07 09:20 UTC, max-java commented on pom.xml
> +                <version>3.0.2</version>
declare versions as properties, and use variables here

2023-02-07 09:20 UTC, max-java commented on pom.xml
> +            </dependency>
you don't need this in dependency management, as it manages by spring bom

2023-02-07 19:54 UTC, Sav4ykVladzislau approved these changes

2023-02-07 20:42 UTC, schneidervs approved these changes

2023-02-09 16:36 UTC, Artem-Metlushko approved these changes

2023-02-09 16:37 UTC, Artem-Metlushko approved these changes

2023-02-09 16:38 UTC, AlexanderYarokhovich approved these changes

2023-02-12 14:53 UTC, max-java approved these changes
lgfm

2023-02-12 14:54 UTC, merged